name: Deploy to Namecheap

on:
    push:
      branches: [ main ]

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Deploy to Namecheap via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: public_html/
          port: 21
          protocol: ftp
          timeout: 60000
          log-level: verbose
